apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddos-simulator
  namespace: ddos
spec:
  schedule: "*/5 * * * *"  # Runs every 15 minutes, adjust as necessary
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            is_anomaly: true
            app: ddos-simulator
        spec:
          containers:
            - name: hey
              image: rakyll/hey
              command: ["sh", "-c", "hey -z 60s -c 50 http://10.0.0.1/red"]
          restartPolicy: OnFailure
