{{- range .Values.namespaces }}

apiVersion: v1
kind: Service
metadata:
  name: back-end
  namespace: {{ . }}
spec:
  type: ClusterIP
  selector:
    app: back-end
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80

---
  {{- end }}