{{- range .Values.namespaces }}

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-namespace-prefix
  namespace: {{ . }}
spec:
  stripPrefix:
    prefixes:
      - "/{{ . }}"
    forceSlash: false  # This prevents Traefik from automatically adding a '/' at the end of the path

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end-{{ . }}
  namespace: {{ . }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    traefik.ingress.kubernetes.io/router.middlewares: "{{ . }}-strip-namespace-prefix@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /{{ . }}
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 5000

---
  {{- end }}