{{- range .Values.namespaces }}

apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ . }}
spec:
  type: ClusterIP
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80

---
  {{- end }}