{{- range .Values.namespaces }}

apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: {{ . }}
spec:
  type: ClusterIP
  selector:
    app: data-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
  {{- end }}