apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-backend-traces-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /traces.csv
        pathType: Prefix
        backend:
          service:
            name: otel-backend
            port:
              number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-backend-predict-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /predict
        pathType: Prefix
        backend:
          service:
            name: otel-backend
            port:
              number: 8000
