apiVersion: v1
kind: Service
metadata:
  name: otel-backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: otel-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
