{{- range .Values.namespaces }}
  
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddos-simulator
  namespace: dos
spec:
  schedule: "*/5 * * * *"  # Runs every 15 minutes, adjust as necessary
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            is_anomaly: true
            app: ddos-simulator
        spec:
          containers:
            - name: hey
              image: rakyll/hey
              command: ["sh", "-c", "hey -z 30s -c 50 http://160.85.252.183/{{ . }}"]
          restartPolicy: OnFailure


---
  {{- end }}